Writing tutorial
McSinyx/palace pull request #104
Opened 2020-05-15 14:55 UTC by Huy-Ngo

2020-05-15 15:01 UTC, McSinyx reviewed
Some early nits.

2020-05-15 15:01 UTC, McSinyx commented on src/tutorial/context.rst
> +---------------------------
Please make sure the under line is under something.

2020-05-15 15:01 UTC, McSinyx commented on src/tutorial/context.rst
> +.. highlight:: python
Please use `code-block` instead.

2020-05-15 15:01 UTC, McSinyx commented on src/tutorial/context.rst
> +
Pay attention to spacing.

2020-05-15 15:01 UTC, McSinyx commented on src/tutorial/context.rst
> +           # Your code goes here
Note the indentation here.

2020-05-15 15:06 UTC, Huy-Ngo commented on src/tutorial/context.rst
> +---------------------------
Hmm... the syntax highlighting enlarged the text so I couldn't see it.

2020-05-16 09:02 UTC, McSinyx commented on src/tutorial/context.rst
> +
There should be a newline after this, however sphinx would tell you when you build so...

2020-05-17 13:47 UTC, McSinyx commented
IMHO you should keep the documentation process incremental.  While there's not much to review, it'd still be difficult to review more than a few pages of tutorial at a time.

2020-05-18 01:15 UTC, Huy-Ngo commented
By incremental you mean adding only one or a few pages at a time?

2020-05-18 08:45 UTC, McSinyx commented
Try not adding new pages and finish the existing ones.

2020-05-19 02:08 UTC, McSinyx requested changes

2020-05-19 02:08 UTC, McSinyx commented on src/tutorial/play-audio.rst
> +	   dec.play(12000, 4, src)
Please pay attention to indentation.  Too bad I'm not aware of any linter that can do this.  Also I feel the newline between the `fname` (use `filename` please BTW) assignment and the `with` statement is excessive.

2020-05-19 02:08 UTC, McSinyx commented on src/tutorial/play-audio.rst
> +`Context` has a method, `update()`, which update itself and the source.
ReST uses double tick for fixed width text, however it's a lot better if you can use the `:py:...` like in design principles.  Moreover, please separate sentences by 2 spaces.

2020-05-19 02:08 UTC, McSinyx commented on src/tutorial/play-audio.rst
> +Decode the audio file
Please use title case for headings.

2020-05-19 02:08 UTC, McSinyx commented on src/tutorial/index.rst
> +..
Please remove this last line.

2020-05-19 02:08 UTC, McSinyx commented on src/tutorial/context.rst
> +   with Device(), Context() as ctx:
Missing highlight, also `Context()` does not work (yet, and I don't think it's a good idea either).

2020-05-19 02:48 UTC, McSinyx requested changes

2020-05-19 02:48 UTC, McSinyx commented on src/tutorial/context.rst
> +the `Device` class.
Missing reference here, actually in the entire page.

2020-05-19 02:48 UTC, McSinyx commented on src/tutorial/play-audio.rst
> +:py:class:`Context` has a method, :py:meth:`update`, which update itself and the source.
It's `` :py:meth:`Context.update` ``.

2020-05-19 02:48 UTC, McSinyx commented on src/tutorial/play-audio.rst
> +is to :py:func:`sleep` for a while.
We don't generate reference for standard modules, just use  double backtick here.

2020-05-19 02:49 UTC, McSinyx commented on src/tutorial/play-audio.rst
> +`Context` has a method, `update()`, which update itself and the source.
Ping on the sentence separation thing.

2020-05-19 03:34 UTC, McSinyx approved these changes

2020-05-19 10:03 UTC, merged