Create FUNDING.yml
McSinyx/palace pull request #117
Opened 2020-08-24 14:53 UTC by McSinyx

2020-08-26 06:36 UTC, Huy-Ngo approved these changes

2020-08-26 08:00 UTC, 9a24f0 commented
No

2020-08-29 02:52 UTC, Huy-Ngo requested changes

2020-08-29 02:52 UTC, Huy-Ngo commented on .github/FUNDING.yml
> +patreon: # Replace with a single Patreon username
```suggestion
patreon: __huy_ngo__
```

2020-08-30 10:51 UTC, Huy-Ngo approved these changes

2020-09-04 03:05 UTC, 9a24f0 commented
I'll adding funding information later

2020-09-04 03:06 UTC, merged