Fix ChorusEffect
McSinyx/palace pull request #91
Opened 2020-04-29 04:48 UTC by 9a24f0

2020-04-29 04:56 UTC, McSinyx requested changes
The same for others accordingly.  Rmb to pull --rebase from master since branch mismatch.

2020-04-29 04:56 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid phase: {value}')
```suggestion
        if value < -180 or value > 180:
            raise ValueError(f'invalid phase: {value}')
        self.properties.phase = value
```

2020-04-30 12:51 UTC, McSinyx commented
Gentle ping!

2020-05-03 04:59 UTC, McSinyx commented
Dude, is everything OK?

2020-05-03 10:19 UTC, Huy-Ngo commented
Something wrong? @9a24f0

2020-05-03 13:33 UTC, McSinyx commented
`git pull --rebase origin master` please, too noisy to be reviewed.

2020-05-03 13:35 UTC, 9a24f0 commented
> `git pull --rebase origin master` please, too noisy to be reviewed.

I did .-.

2020-05-03 13:43 UTC, McSinyx approved these changes
> I did .-.

I've just ran the command and look how clean the diff is now.  You sure you had the `--rebase` flague?  Anyway LGTM, if Travis agree.  This one should be squashed together though.

2020-05-03 13:46 UTC, 9a24f0 commented
> > I did .-.
> 
> I've just ran the command and look how clean the diff is now. You sure you had the `--rebase` flague? Anyway LGTM, if Travis agree. This one should be squashed together though.

Idk why I got those mess .-. But I clearly did `git pull --rebase origin master`. After that, git keep saying that my current branch is behind so I have to pull from this branch, that's why I even have the `resolve conflicts` commit before :/

2020-05-03 13:53 UTC, merged

2020-05-03 14:01 UTC, McSinyx commented
Strange, maybe not being a weeb gaining be the power of getting things done first try lmao.  No worries tho.