Fix ReverbEffect
McSinyx/palace pull request #96
Opened 2020-05-03 15:42 UTC by 9a24f0

2020-05-03 15:57 UTC, McSinyx requested changes

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +from numpy import linalg as LA
no

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Gain HF, from 0.0 to 1.0."""
It's high frequency gain

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid gain hf: {value}')
Same here.

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Gain LF, from 0.0 to 1.0."""
Here too.

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid gain lf: {value}')
aussi

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Decay HF ratio, from 0.1 to 20.0."""
another one

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid decay hf ratio: {value}')
DJ Khalid

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Decay LF ratio, from 0.1 to 20.0."""
Rick Ross

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid decay lf ratio: {value}')
Mayback Music

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Reflections pan, 3D vector of magnitude between 0 and 1."""
```suggestion
        """Reflections pan as 3D vector of magnitude between 0 and 1."""
```

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
>          self.properties.reflections_pan[2] = value[2]
```python
x, y, z = value
magnitude = x*x + y*y + z*z
if ...
    raise...
... = x
...
```

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Late reverb pan, 3D vector of magnitude between 0 and 1."""
```suggestion
        """Late reverb pan as a 3D vector of magnitude between 0 and 1."""
```

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
>          self.properties.late_reverb_pan[2] = value[2]
same as above

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Air absorption gain, from 0.892 to 1.0."""
high frequency*

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid air absorption gain hf: {value}')
same as above

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """HF reference, from 1000.0 to 20000.0."""
we the best music

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid hf reference: {value}')
kiss the ring

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """LF reference, from 20.0 to 1000.0."""
we the best forever

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +            raise ValueError(f'invalid lf reference: {value}')
I'm on one

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
> +        """Decay HF limit, either TRUE or FALSE."""
high frequency*

2020-05-03 15:57 UTC, McSinyx commented on src/palace.pyx
>          self.properties.decay_hf_limit = value
I'm not sure about this, maybe just `self.properties.decay_hf_limit = bool(value)` is enough.

2020-05-03 16:27 UTC, 9a24f0 commented on src/palace.pyx
>          self.properties.reflections_pan[2] = value[2]
u forgot the sqrt LOL

2020-05-04 08:51 UTC, McSinyx commented on src/palace.pyx
>          self.properties.reflections_pan[2] = value[2]
well yes but actually no

2020-05-04 09:41 UTC, McSinyx commented on src/palace.pyx
> +        """High frequency decay limit, either TRUE or FALSE."""
Drop the `, either TRUE or FALSE`, the annotation is enough.

2020-05-04 10:41 UTC, McSinyx requested changes
Could you please check if the result of `fx.decay_hf_limit` is a `bool`, i.e. replace the existing `assert` with `assert fx.decay_hf_limit is True`, etc.

2020-05-04 14:35 UTC, McSinyx commented on src/palace.pyx
>          return True if self.properties.decay_hf_limit else False
Ugh missed this til now, what an abomination.  Please change it to `bool(self.properties.decay_hf_limit)`.

2020-05-04 14:45 UTC, McSinyx commented
Niting on the commit message, please use proper casing (GH-*), and do me a favor by skipping the PR ref, since you can find it when you're on the commit page anyway, e.g.
```diff
-Fix ChorusEffect (#91)
+Fix ChorusEffect
```

2020-05-04 15:17 UTC, McSinyx approved these changes

2020-05-04 15:32 UTC, merged